# Generated by Django 3.2.5 on 2021-08-05 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='no name', max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('country', models.CharField(default='no countrt', max_length=1000)),
                ('gender', models.CharField(default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='no name', max_length=1000)),
                ('password', models.CharField(max_length=1000)),
                ('country', models.CharField(default='no country', max_length=1000)),
                ('gender', models.CharField(default='M', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title', max_length=30)),
                ('content', models.CharField(default='empty post', max_length=10000)),
                ('date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Post Date')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental_health_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor_Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title', max_length=30)),
                ('content', models.CharField(default='empty post', max_length=10000)),
                ('date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Post Date')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental_health_app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Booking Date')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental_health_app.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental_health_app.patient')),
            ],
        ),
    ]
